### ISSUE TITLE
Start portfolio from scratch using CRA

### ISSUE THREAD

**Issue by jackwkinsey** [jackwkinsey/work-portfolio#1]
## Overview

The ACG course on AWS was a good start to show how to get a project up and running and it made sense to add React manually, but I'd rather have some things setup out of the box and "Create React App" (CRA) does that for me. So I want to essentially "gut" this repo and use CRA to setup a base project to continue working on.

## Acceptance Criteria

- [x] Current code base is gutted and removed
- [x] New app is created using Create React App
- [x] Base app is committed and ready for work
- [x] Display a "Coming soon" or "Under Construction" message since this will go live before finished

## Tasks

- [x] Remove all source code from ACG course (with the exception of the buildspec.yaml and upload.py files)
- [x] Use CRA to create base React app shell

## Notes

This work will be done on a new branch so pushes shouldn't show up live until merged with master
