### ISSUE TITLE
Add About section

### ISSUE THREAD

**Issue by jackwkinsey** [jackwkinsey/work-portfolio#3]
## Overview

The About section is the top section of the site and allows me to introduce myself to potential employers and clients. It should contain my professional headshot and a short blurb about me. Also need to setup fonts to be used from Google Fonts.

---

### Acceptance Criteria

- [x] About section added
- [x] About section contains circular headshot image
- [x] About section contains text about me
- [x] Google Fonts added

### Tasks

- [x] Remove React logo and favicon
- [x] Remove "Under Construction" text
- [x] Change page title to "Jack Kinsey | Software Engineer"
- [x] Add headshot image file
- [x] Add About section
- [x] Figure out what the About section text should say and add to section
- [x] Add headshot image with round border to section
- [x] Add Oswald, Lato, & Source Code Pro fonts from Google Fonts
