### ISSUE TITLE
Add Links section

### ISSUE THREAD

**Issue by jackwkinsey** [jackwkinsey/work-portfolio#4]
## Overview

There should be a section at the bottom of the page that contains all of the links that visitors will probably care about:

- LinkedIn
- GitHub
- Resume download

---

### Acceptance Criteria

- [x] A section has been added to the bottom of the page that has my LinkedIn, GitHub, and resume download links contained within

### Tasks

- [x] Add updated resume file to project
- [x] Add my font awesome pro icons to project (via npm?)
- [x] Add section to contain links (social links?)
- [x] Use GitHub icon for GitHub link, LinkedIn icon for LinkedIn link, and either document icon or a download icon for resume link
