### ISSUE TITLE
Add Projects section

### ISSUE THREAD

**Issue by jackwkinsey** [jackwkinsey/work-portfolio#5]
## Overview

I need a Projects section to showcase some of my work. To do this I'd like to have "bubbles" that contain a relevant background image with some basic information text overlaid (title only?). The "bubble" can be clicked to display a modal that displays more information about the project. 

---

### Acceptance Criteria

- [ ] Projects section added that contains at least 3 project "bubbles" that can be interacted with

### Tasks

- [ ] Create a component that can be reused for each "project bubble".
- [ ] Clicking a project bubble sets the currently viewed project to clicked project & opens a modal that contains info for the currently viewed project.
- [ ] Create a reusable modal component to hold project information for currently view project.
