### ISSUE TITLE
Update favicon to personal logo

### ISSUE THREAD

**Issue by jackwkinsey** [jackwkinsey/work-portfolio#7]
## Overview

The current favicon on my machine shows the react logo still. I don't think others will see this, but I don't want an empty favicon logo either. I should add a logo based on my initials that I've made in the past.

---

### Acceptance Criteria

- [x] Site has custom favicon

### Tasks

- [x] Create favicon image
- [x] Add to project and reference in `index.html`
